version: '3.8'
services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    environment:
      - SA_PASSWORD=p@ssw0rD!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  backend:
    build:
      context: .
      dockerfile: Backend.dockerfile
    container_name: backend
    ports:
      - "9090:9090"
    volumes:
      - ./src/:/app/db_benchmark_stuff/src/:ro
