version: '3.8'
services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    environment:
      - SA_PASSWORD=p@ssw0rD!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
